### ISSUE TITLE
Bad Gateway: Error 502 using docker-compose.yml

### ISSUE THREAD

**Issue by riaanvddool** [bennibu/ushahidi-bundle#1]
I get `Bad Gateway: Error 502` when using `docker-compose up`.

My `docker-compose.yml`:

```
version: "2"

services:
  platform:
    image: bennibu/ushahidi-platform
    ports:
      - 8080:80
    environment:
      DB_HOST: mariadb
      DB_NAME: ushahidi
      DB_TYPE: MySQLi
      DB_USER: root
      DB_PASS: secret
      http_proxy: ${http_proxy}
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.1.16
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ushahidi

  client:
    image: bennibu/ushahidi-client
    ports:
      - 8081:80
    environment:
      BACKEND_URL: http://localhost:8080/
      http_proxy: ${http_proxy}

volumes:
  mariadb:
```
